# Generated by Django 2.1.3 on 2018-12-04 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000, verbose_name='user_id')),
                ('deal_id', models.IntegerField(verbose_name='deal_id')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time')),
            ],
        ),
    ]
