# Generated by Django 2.1.3 on 2018-12-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_auto_20181204_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user_id',
            field=models.CharField(max_length=32, verbose_name='user_id'),
        ),
    ]
